import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

class FirestoreService {
  // 1. Establish database instance references
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Creates the user profile document for a freshly registered account.
  Future<bool> createUserProfile({
    required String uid,
    required String fullName,
    required String email,
    required String phone,
    required String district,
    required String userType,
  }) async {
    try {
      await _db.collection('users').doc(uid).set({
        'fullName': fullName,
        'email': email,
        'phone': phone,
        'district': district,
        'userType': userType,
        'createdAt': FieldValue.serverTimestamp(),
      });
      debugPrint('FirestoreService: User profile created for $uid.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error creating user profile: $e');
      return false;
    }
  }

  /// Saves a maize diagnostic record to the user's scan history collection.
  Future<bool> saveScanRecord({
    required String imageUrl,
    required String classificationLabel,
    required double confidenceScore,
    String? location,
  }) async {
    try {
      final User? currentUser = _auth.currentUser;
      if (currentUser == null) {
        debugPrint('FirestoreService: Cannot save record, no authenticated user found.');
        return false;
      }

      // 2. Target path: users -> [userUid] -> scans -> [autoGeneratedDocId]
      final CollectionReference userScans = _db
          .collection('users')
          .doc(currentUser.uid)
          .collection('scans');

      await userScans.add({
        'imageUrl': imageUrl,
        'label': classificationLabel,
        'confidence': confidenceScore,
        'location': location,
        'timestamp': FieldValue.serverTimestamp(), // Ensures uniform timeline ordering
      });

      debugPrint('FirestoreService: Scan successfully logged.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error saving log: $e');
      return false;
    }
  }

  /// Deletes a single scan record from the active logged-in user's scan history.
  Future<bool> deleteScanRecord(String scanId) async {
    try {
      final User? currentUser = _auth.currentUser;
      if (currentUser == null) {
        debugPrint('FirestoreService: Cannot delete record, no authenticated user found.');
        return false;
      }

      await _db
          .collection('users')
          .doc(currentUser.uid)
          .collection('scans')
          .doc(scanId)
          .delete();

      debugPrint('FirestoreService: Scan $scanId deleted.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error deleting scan: $e');
      return false;
    }
  }

  /// Updates the active logged-in user's editable profile fields.
  Future<bool> updateUserProfile({
    required String fullName,
    required String phone,
    required String district,
    String? photoUrl,
    bool removePhoto = false,
  }) async {
    try {
      final User? currentUser = _auth.currentUser;
      if (currentUser == null) {
        debugPrint('FirestoreService: Cannot update profile, no authenticated user found.');
        return false;
      }

      await _db.collection('users').doc(currentUser.uid).update({
        'fullName': fullName,
        'phone': phone,
        'district': district,
        if (removePhoto) 'photoUrl': FieldValue.delete() else 'photoUrl': ?photoUrl,
      });

      bool authProfileChanged = false;
      if (fullName.isNotEmpty && currentUser.displayName != fullName) {
        await currentUser.updateDisplayName(fullName);
        authProfileChanged = true;
      }
      if (removePhoto) {
        await currentUser.updatePhotoURL(null);
        authProfileChanged = true;
      } else if (photoUrl != null) {
        await currentUser.updatePhotoURL(photoUrl);
        authProfileChanged = true;
      }
      // updateDisplayName/updatePhotoURL don't refresh the locally cached
      // currentUser object on their own — without this, any code reading
      // FirebaseAuth.instance.currentUser.photoURL/displayName right after
      // this call (e.g. as a fallback when the Firestore field is absent)
      // would still see the old value until the app restarted.
      if (authProfileChanged) {
        await currentUser.reload();
      }

      debugPrint('FirestoreService: User profile updated for ${currentUser.uid}.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error updating user profile: $e');
      return false;
    }
  }

  /// Streams the active logged-in user's profile document (full name, district, etc.).
  Stream<DocumentSnapshot<Map<String, dynamic>>> getUserProfile() {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      return const Stream.empty();
    }

    return _db.collection('users').doc(currentUser.uid).snapshots();
  }

  /// Streams real-time scan history documents matching the active logged-in user account.
  Stream<QuerySnapshot> getUserScanHistory() {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      // Returns an empty stream if unexpected guest fallback occurs
      return const Stream.empty();
    }

    return _db
        .collection('users')
        .doc(currentUser.uid)
        .collection('scans')
        .orderBy('timestamp', descending: true) // Newest diagnostics pop up on top
        .snapshots();
  }
}