import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

import '../utils/scan_classification.dart';

class FirestoreService {
  // 1. Establish database instance references
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Creates the user profile document for a freshly registered account.
  Future<bool> createUserProfile({
    required String uid,
    required String fullName,
    required String email,
    required String phone,
    required String district,
    required String userType,
  }) async {
    try {
      await _db.collection('users').doc(uid).set({
        'fullName': fullName,
        'email': email,
        'phone': phone,
        'district': district,
        'userType': userType,
        'createdAt': FieldValue.serverTimestamp(),
      });
      debugPrint('FirestoreService: User profile created for $uid.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error creating user profile: $e');
      return false;
    }
  }

  /// Fetches the profile document for the currently signed-in user.
  Future<Map<String, dynamic>?> getUserProfile() async {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) return null;

    try {
      final doc = await _db.collection('users').doc(currentUser.uid).get();
      return doc.data();
    } catch (e) {
      debugPrint('FirestoreService Error fetching user profile: $e');
      return null;
    }
  }

  /// Saves a maize diagnostic record to the user's scan history collection.
  Future<bool> saveScanRecord({
    required String imageUrl,
    required String classificationLabel,
    required double confidenceScore,
    String? location,
  }) async {
    try {
      final User? currentUser = _auth.currentUser;
      if (currentUser == null) {
        debugPrint('FirestoreService: Cannot save record, no authenticated user found.');
        return false;
      }

      // 2. Target path: users -> [userUid] -> scans -> [autoGeneratedDocId]
      final CollectionReference userScans = _db
          .collection('users')
          .doc(currentUser.uid)
          .collection('scans');

      await userScans.add({
        'imageUrl': imageUrl,
        'label': classificationLabel,
        'confidence': confidenceScore,
        'location': location,
        'timestamp': FieldValue.serverTimestamp(), // Ensures uniform timeline ordering
      });

      debugPrint('FirestoreService: Scan successfully logged.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error saving log: $e');
      return false;
    }
  }

  /// Computes total/healthy/at-risk scan counts for the signed-in user.
  Future<({int total, int healthy, int atRisk})> getUserScanStats() async {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) return (total: 0, healthy: 0, atRisk: 0);

    try {
      final snapshot = await _db
          .collection('users')
          .doc(currentUser.uid)
          .collection('scans')
          .get();

      int atRisk = 0;
      for (final doc in snapshot.docs) {
        final label = (doc.data()['label'] as String?) ?? '';
        if (isHighRiskLabel(label)) atRisk++;
      }

      final total = snapshot.docs.length;
      return (total: total, healthy: total - atRisk, atRisk: atRisk);
    } catch (e) {
      debugPrint('FirestoreService Error fetching scan stats: $e');
      return (total: 0, healthy: 0, atRisk: 0);
    }
  }

  /// Streams real-time scan history documents matching the active logged-in user account.
  Stream<QuerySnapshot> getUserScanHistory() {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      // Returns an empty stream if unexpected guest fallback occurs
      return const Stream.empty();
    }

    return _db
        .collection('users')
        .doc(currentUser.uid)
        .collection('scans')
        .orderBy('timestamp', descending: true) // Newest diagnostics pop up on top
        .snapshots();
  }
}