import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';

class FirestoreService {
  // 1. Establish database instance references
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Saves a maize diagnostic record to the user's scan history collection.
  Future<bool> saveScanRecord({
    required String imageUrl,
    required String classificationLabel,
    required double confidenceScore,
  }) async {
    try {
      final User? currentUser = _auth.currentUser;
      if (currentUser == null) {
        debugPrint('FirestoreService: Cannot save record, no authenticated user found.');
        return false;
      }

      // 2. Target path: users -> [userUid] -> scans -> [autoGeneratedDocId]
      final CollectionReference userScans = _db
          .collection('users')
          .doc(currentUser.uid)
          .collection('scans');

      await userScans.add({
        'imageUrl': imageUrl,
        'label': classificationLabel,
        'confidence': confidenceScore,
        'timestamp': FieldValue.serverTimestamp(), // Ensures uniform timeline ordering
      });

      debugPrint('FirestoreService: Scan successfully logged.');
      return true;
    } catch (e) {
      debugPrint('FirestoreService Error saving log: $e');
      return false;
    }
  }

  /// Streams real-time scan history documents matching the active logged-in user account.
  Stream<QuerySnapshot> getUserScanHistory() {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      // Returns an empty stream if unexpected guest fallback occurs
      return const Stream.empty();
    }

    return _db
        .collection('users')
        .doc(currentUser.uid)
        .collection('scans')
        .orderBy('timestamp', descending: true) // Newest diagnostics pop up on top
        .snapshots();
  }
}