// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8Ztm5kELuH_KtTr2jv83qr7zB2vAh1U',
    appId: '1:530780315531:web:d208ea681069e09c2a998e',
    messagingSenderId: '530780315531',
    projectId: 'aflalert',
    authDomain: 'aflalert.firebaseapp.com',
    storageBucket: 'aflalert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUquvPfpCkHplnUvPcN08AQLIIrAkb5UU',
    appId: '1:530780315531:android:2ba21809659901222a998e',
    messagingSenderId: '530780315531',
    projectId: 'aflalert',
    storageBucket: 'aflalert.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWB6Dj_OyLLc0BfQUexTJghDJ5RrOqV_U',
    appId: '1:530780315531:ios:fa91dd48ea1d64452a998e',
    messagingSenderId: '530780315531',
    projectId: 'aflalert',
    storageBucket: 'aflalert.firebasestorage.app',
    iosBundleId: 'com.aflalert.aflalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8Ztm5kELuH_KtTr2jv83qr7zB2vAh1U',
    appId: '1:530780315531:web:8c971bf89f1f83f92a998e',
    messagingSenderId: '530780315531',
    projectId: 'aflalert',
    authDomain: 'aflalert.firebaseapp.com',
    storageBucket: 'aflalert.firebasestorage.app',
  );
}
